
- name: set zookeeper fact
  set_fact: zookeeper_installed=True

#- name: Create service account for Zookeeper
#  user: name={{ zookeeper.user }}
#        system=yes
#        shell={{ zookeeper.user_shell }}
#        state=present
#        groups="{{ zookeeper.user_groups | join(',') }}"

- name: create install directory
  file:
    path: "{{ install_dir }}/{{ zookeeper.zookeeper_install_dir }}"
    state: directory
#    owner: "{{ zookeeper.user }}"
#    group: "{{ zookeeper.user }}"
#  become: true

- name: create data directory
  file:
    path: "{{ zookeeper.data_dir }}"
    state: directory
    mode: 0777
#    owner: "{{ zookeeper.user }}"
#    group: "{{ zookeeper.user }}"
#  become: true

- debug:
     msg: "Downloading zookeeper as {{ zookeeper.download_location }}/{{ zookeeper.zookeeper_archive }}"

- name: download zookeeper
  get_url: 
    url: "{{ zookeeper.download_location }}/{{ zookeeper.zookeeper_archive }}" 
    dest: "{{ install_temp_dir }}/{{ zookeeper.zookeeper_archive }}"
  register: get_url_result
  until: get_url_result is succeeded
  retries: "{{ download_retries }}"
  delay: 10

- name: unarchive to the install directory
  unarchive:
    src: "{{ install_temp_dir }}/{{ zookeeper.zookeeper_archive }}"
    dest: "{{ install_dir }}/{{ zookeeper.zookeeper_install_dir }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: set zookeeper configuration
  template: src="zoo.cfg.j2" dest="{{ install_dir }}/{{ zookeeper.zookeeper_install_dir }}/conf/zoo.cfg"

- name: set zookeeper node id
  template: src="myid.j2" dest="{{ zookeeper.data_dir }}/myid"

# Environment setup.
- name: add zookeeper profile to startup
  template:
    src: zookeeper-profile.sh.j2
    dest: /etc/profile.d/zookeeper-profile.sh
    mode: 0644
