---
- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: install os dependencies
  yum:
   name: 
     - gcc
     - openssl-devel
     - libffi-devel 
     - python-devel
     - openssl-devel
     - libcurl
     - libcurl-devel
   state: present

- name: Remove epel repository
  yum_repository:
    name: epel
    state: absent

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
