---
# Install and configure proxy certificates for RHEL server
# Blake C. Fleischer, 8 Nov 2018


- name: update trusted ca debian
  shell: /usr/sbin/update-ca-certificates
  when: ansible_os_family == "Debian"
  become: yes
  become_user: root

- name: update trusted ca redhat
  shell: /bin/update-ca-trust
  when: ansible_os_family == "RedHat"
  become: yes
  become_user: root
