- name: set kafka fact
  set_fact: kafka_installed=True

#- name: Create service account for kafka
#  user: name={{ kafka.user }}
#        system=yes
#        shell={{ kafka.user_shell }}
#        state=present
#        groups="{{ kafka.user_groups | join(',') }}"

- name: create install directory
  file:
    path: "{{ install_dir }}/{{ kafka.kafka_install_dir }}"
    state: directory
#    owner: "{{ kafka.user }}"
#    group: "{{ kafka.user }}"
#  become: true

- name: create log directory
  file:
    path: "{{ install_dir }}/{{ kafka.kafka_install_dir }}/logs"
    state: directory
#    owner: "{{ kafka.user }}"
#    group: "{{ kafka.user }}"
#  become: true

- name: create data directory
  file:
    path: "{{ kafka.data_dir }}"
    state: directory
#    owner: "{{ kafka.user }}"
#    group: "{{ kafka.user }}"
#  become: true

- debug:
    msg: "Downloading kafka {{ kafka.download_location }}/{{ kafka.kafka_archive }}"

- name: download kafka
  get_url: 
    url: "{{ kafka.download_location }}/{{ kafka.kafka_archive }}" 
    dest: "{{ install_temp_dir }}/{{ kafka.kafka_archive }}"
  register: get_url_result
  until: get_url_result is succeeded
  retries: "{{ download_retries }}"
  delay: 10

- name: unarchive to the install directory
  unarchive:
    src: "{{ install_temp_dir }}/{{ kafka.kafka_archive }}"
    dest: "{{ install_dir }}/{{ kafka.kafka_install_dir }}"
    remote_src: yes
    extra_opts: 
      - --strip-components=1

- name: set kafka configuration
  template: src="server.properties.j2" dest="{{ install_dir }}/{{ kafka.kafka_install_dir }}/config/server.properties"

# Environment setup.
- name: add kafka profile to startup
  template:
    src: kafka-profile.sh.j2
    dest: /etc/profile.d/kafka-profile.sh
    mode: 0644

# Install KafkaT
- name: enable rhel-server-optional repo
  ini_file:
    dest: /etc/yum.repos.d/redhat-rhui.repo
    section: rhui-REGION-rhel-server-optional
    option: enabled
    value: "1"
  #yum_repository:
  #  name: rhui-REGION-rhel-server-optional
  #  description: Red Hat Enterprise Linux Server 7 Optional (RPMs)
  #  mirrorlist: https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/$releasever/$basearch/optional/os
  #  enabled: yes
  #  gpgcheck: 1
  #  gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  # rhsm_repository:
  #   name: rhui-REGION-rhel-server-optional
  #   state: enabled

- name: install KafkaT dependencies
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - ruby-devel
    - rubygems
    - make
    - automake
    - gcc
    - gcc-c++
    - kernel-devel

- name: disable rhel-server-optional repo
  ini_file:
    dest: /etc/yum.repos.d/redhat-rhui.repo
    section: rhui-REGION-rhel-server-optional
    option: enabled
    value: "0"

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: install KafkaT asyncronous
  gem:
    name: kafkat
    repository: https://rubygems.org
    state: present
    build_flags: 
      - "--no-ri"
      - "--no-rdoc"
  environment:
    PATH: "{{ ansible_env.PATH }}:/root/.gem/ruby/bin"
  async: 1000
  poll: 5
  register: kafka_sleeper

- name: check KafkaT install asynchronously
  async_status:
    jid: "{{ kafka_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: set KafkaT configuration
  template: src="kafkatcfg.j2" dest="/etc/kafkatcfg"
