---
# Install and configure proxy certificates a for RHEL server
# Blake C. Fleischer, 8 Nov 2018

- name: Install ca package
  package:
    name: ca-certificates
    state: present
  become: yes
  become_user: root

#- debug:
#    msg:
#      - "ca_path = {{ ca_path }}"
#      - "ansible_os_family = {{ [ansible_os_family] }}"
#      - "ansible_distribution_major_version|int = {{ [ansible_distribution_major_version|int] }}"
#      - "{{ ca_path[ansible_os_family] }}"
#      - "{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/"

- name: Copy ca certs and update trusted certs
  copy:
    src: '{{ item }}'
    dest: '{{ ca_path[ansible_os_family] }}' #'{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/'
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/certs/*
  notify:
    - update trusted ca debian
    - update trusted ca redhat
  become: yes
  become_user: root
  when: proxy_config.do_proxy|bool

# Environment setup.
- name: Set proxy vars for all users
  template:
    src: proxy_config.sh.j2
    dest: /etc/profile.d/proxy_config.sh
    mode: 0644

- name: Edit sudoers file to env_keep http_proxy
  lineinfile:
    dest: /etc/sudoers
    state: present
    insertafter: '^# Defaults   env_keep'
    line: 'Defaults    env_keep += "http_proxy https_proxy HTTP_PROXY HTTPS_PROXY"'

- name: Copy Python proxy script
  copy:
    src: 'files/proxyfix/proxyfix.py'
    dest: '/usr/local/bin/'
    owner: '{{ default_username }}'
    group: 'users'
    mode: 0755
  become: yes
  become_user: root

- name: Configure Python proxy via proxy script
  command: "/usr/local/bin/proxyfix.py --cert_path {{ ca_path[ansible_os_family] }} --pip --requests"
  become: yes
  become_user: root
  when: proxy_config.do_proxy|bool
