
#- name: remove old java packages from OS
#  shell:
#     yum erase -y java-1.8.0-openjdk java-1.8.0-openjdk-headless

#- name: set java distribution fact
#  set_fact: java_install_file=jdk-{{ common.java_version }}-linux-x64.rpm
#
#- name: remove old java packages
#  file: path="{{ install_temp_dir }}/{{ java_install_file }}" state=absent
#
#- debug:
#   msg: "Downloading {{ common.java_download }}"

#- name: download java sdk rpm
#  get_url:
#     headers:
#       Cookie: "oraclelicense=accept-securebackup-cookie"
#     url: "{{ common.java_download }}"
#     dest: "{{ install_temp_dir }}/{{ java_install_file }}"

#- name: download java sdk rpm
#  shell: "cd {{ install_temp_dir }} && curl -LO {{ common.java_download }} -H 'Cookie: oraclelicense=accept-securebackup-cookie'"

#- name: install java sdk rpm
#  shell: "rpm -Uvh --replacepkgs {{ install_temp_dir }}/{{ java_install_file }}"
#  register: shell_result
#  failed_when: "'error' in shell_result.stderr"

#- name: set java jce distribution fact
#  set_fact: java_jce_install_file=jce_policy-8.zip
#
#- name: download java jce zip
#  get_url:
#     headers:
#       Cookie: "oraclelicense=accept-securebackup-cookie"
#     url: "{{ common.java_jce_download }}"
#     dest: "{{ install_temp_dir }}/{{ java_jce_install_file }}"
#
#- name: update java with jce contents
#  shell:
#    unzip -o -j -q {{ install_temp_dir }}/{{ java_jce_install_file }} -d {{ common.java_home }}/jre/lib/security/

- name: install openjdk
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - "java-{{ common.java_major_version }}-openjdk-{{ common.java_minor_version }}*"
    - "java-{{ common.java_major_version }}-openjdk-headless-{{ common.java_minor_version }}*"
    - "java-{{ common.java_major_version }}-openjdk-devel-{{ common.java_minor_version }}*"

- name: configure default java
  shell: "alternatives --install /usr/bin/java java {{ common.java_home }}/bin/java 1"

- name: configure default java
  shell: "alternatives --set java {{ common.java_home }}/bin/java"

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is not defined and java_home == ''
