- name: Update repository subscription on FYRE
  shell:
     cd /etc/yum.repos.d ; rm -f devit-rh7-x86_64.repo* ; wget fyreyum1.fyre.ibm.com/redhat/devit-rh7-x86_64.repo; sed -i 's/enabled = 1/enabled = 0/' /etc/yum/pluginconf.d/rhnplugin.conf
  when: ansible_domain is search("fyre.ibm.com")

- name: install commonly used os dependencies
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - unzip
    - bzip2
    - gcc
    - openssl-devel
    - libffi-devel
    - python-devel
    - openssl-devel
    - libcurl
    - libcurl-devel
    - patch

      #- name: upgrade all packages
      #  shell:
      #     yum update -y

# Install pdsh from EPEL
- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: install epel packages
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - pdsh

- name: Remove epel repository
  yum_repository:
    name: epel
    state: absent

# Clean up
#- name: clean yum repository # Will not be added to ansible as a non yum command because it's not idempotent
#  shell: "yum clean all"

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no


