
- name: set elastic search fact
  set_fact: elastic_search_installed=True

- name: Create service account for Elasticsearch
  user: name="{{ elasticsearch.user }}"
        system=yes
        shell="{{ elasticsearch.user_shell }}"
        state=present
        groups="{{ elasticsearch.user_groups | join(',') }}"

- debug:
     msg: "Downloading ElasticSearch {{ elasticsearch.download_location }}/{{ elasticsearch.es_archive }}"

- name: check elasticsearch downloaded
  local_action: >
    command test -f {{ install_temp_dir }}/{{ elasticsearch.es_archive }}
  register: elasticsearch_downloaded
  failed_when: elasticsearch_downloaded.rc not in [0, 1]
  changed_when: False
  run_once: true

- name: download elasticsearch
  get_url: 
    url: "{{ elasticsearch.download_location }}/{{ elasticsearch.es_archive }}"
    dest: "{{ install_temp_dir }}/{{ elasticsearch.es_archive }}"
  register: get_url_result
  until: get_url_result is succeeded
  retries: "{{ download_retries }}"
  delay: 10
  when: elasticsearch_downloaded.rc == 1
  run_once: true

- name: unarchive to the install directory
  unarchive:
    src: "{{ install_temp_dir }}/{{ elasticsearch.es_archive }}"
    dest: "{{ install_dir }}"
    creates: "{{ install_dir }}/{{ elasticsearch.es_install_dir }}"

- name: set elasticsearch.yml
  template: src="elasticsearch.yml.j2" dest="{{ install_dir }}/{{ elasticsearch.es_install_dir }}/config/elasticsearch.yml"

# Environment setup.
- name: add elasticsearch profile to startup
  template:
    src: elasticsearch-profile.sh.j2
    dest: /etc/profile.d/elasticsearch-profile.sh
    mode: 0644

#- name: make elasticsearch a service
#  shell: >
#    chkconfig --add elasticsearch
